version: "3"
services:
    mysqldb:
      image: mysql:latest
      networks:
        - yos_database-mysql
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_USER=springuser
        - MYSQL_PASSWORD=ThePassword
        - MYSQL_DATABASE=yos_database
        - MYSQL_ROOT_HOST=%

    yos_database:
      image: kanton99/yos_database
      ports:
        - 8070:8080
      networks:
        - yos_database-mysql
      depends_on:
        - mysqldb
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/yos_database
        spring_jpa_hibernate_ddl-auto: create
networks:
  yos_database-mysql: 
    driver: bridge
