server:
  port: ${PORT:8014}
  servlet:
   context-path: /store

spring:
  cache:
    jcache:
      config: 'classpath:ehcache.xml'
  application:
    name: yourstore-store-service
  liquibase:
    enabled: false
  security:
    basic.enable: false
    oauth2:      
      resourceserver:
        jwt:
          issuer-uri: ${KK_URL:http://localhost}:${KK_PORT:8282}/auth/realms/yourstore
          jwk-set-uri: ${KK_URL:http://localhost}:${KK_PORT:8282}/auth/realms/yourstore/protocol/openid-connect/certs

#  data:
#    rest:
#      basePath: /store
  jpa:
     hibernate:
       show-sql: true
       ddl-auto: none
       naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
     database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
     driverClassName: com.mysql.jdbc.Driver
     url: jdbc:mysql://${DSSTORE_URL:localhost}:${DSSTORE_PORT:3306}/${DSSTORE_NAME:store}
     username: ${DSSTORE_USERNAME:root}
     password: ${DSSTORE_PASSWORD:root}
#     password: ${DSSTORE_PASSWORD:}
     liquibase:
       changeLog: classpath:db/liquibase/update.xml

  h2:
   console:
    enabled: true
    settings:
      web-allow-others: true
    path: /h2-console
  devtools:
    livereload:
      port: 35830

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

springdoc:
  swagger-ui:
    path: /api/swagger-ui.html
  show-actuator: true  

spring.security.oauth2.client.registration.google.redirectUri: http://localhost:8014/store/login/oauth2/code/google
spring.security.oauth2.client.registration.google.client-id: 263224732023-25e5gb80mpcm2niaq8240gmbqasmjvsb.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret: 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

activeMq:
  baseUrl: ${ACTIVEMQ_URL:tcp://localhost:61616}